databases:
  - name: mile
    databaseName: mile
    user: mile_user

services:
  - type: web
    name: mitra
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mile
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false