databases:
  - name: djo
    databaseName: budget_app_3yqk
    user: djo

services:
  - type: web
    name: mitra
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false