databases:
  - name: djo
    databaseName: djo_b6fu
    user: djo_b6fu_user

services:
  - type: web
    name: qr
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djo_b6fu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false